### ISSUE TITLE
Create HOMIE Token ERC20 Smart Contract

### ISSUE THREAD

**Issue by perfectmak** [homiesglobal/homiesglobal#2]
This should be the main ERC20 Token.

> NOTE: I'll advice you go through this blogpost first to get some pointers on how to do this: https://www.chainshot.com/article/deploy-your-own-token

Ideally should be paired on with someone so it can have tests written along.

**Comment by Bezaeel** [comment]
Resources to help get started
https://www.quicknode.com/guides/solidity/how-to-create-and-deploy-an-erc20-token
https://docs.openzeppelin.com/contracts/4.x/erc20
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/ERC20.sol
