### ISSUE TITLE
Create Airdrop Contract

### ISSUE THREAD

**Issue by perfectmak** [homiesglobal/homiesglobal#3]
This:
 - after creation, will own % of total HOMIE token to be airdropped
 - should allow someone to add to the list of whitelisted addresses.
 - should allow someone to swap out address. The previous address should be marked as claimed and the new address added. It is important that this works only if the previous address has not claimed. (nice to have)
 - should allow you to claim your token.
 - should expose methods to know, if an address has claimed this token, how much token they claimed.

Ideally should be paired on with someone so it can have tests written along.

**Comment by harneeblayze** [comment]
Contract State
- list of white listed addresses (Addr -> bool)
- Map list of addresses to boolean so we can skip excess loops (HashMap)
- Claims Map (addr -> bool)



Contract Functions
- claimToken()
        1) check user is whitelisted  
	2) check user has not claimed
	3) transfer token and emit event of claim success

- Admin specific function* swapAddress(newAddress:String, oldAddress:String)
    - 0) confirm sender address is an admin/
    - 1) Confirm old address is white listed.
    - 2) Confirm not claimed
    - 3) swap addresses and emit swap event successful


- Admin specific function* 
- (Retain state)
- addAddress(address:String)
    - 0) confirm sender address is an admin/
    - 1) Confirm new address is not white listed (If address exist in list please bounce the address).
    - 2) add address and emit add event successful
