### ISSUE TITLE
Logic to connect with metamask wallet

### ISSUE THREAD

**Issue by perfectmak** [homiesglobal/homiesglobal#5]
When a button is clicked, ideally we should display an option to either use WalletConnect or Metamask if injected.
But for starters, clicking the button should automatically trigger Metamask connect.

<img width="444" alt="Screenshot 2022-01-11 at 8 09 02 pm" src="https://user-images.githubusercontent.com/3120013/149013789-aee23bd5-5db2-4f4f-a917-da8296b19ded.png">

NOTE: Follow up task to this is #6.

**Comment by perfectmak** [comment]
Interested in working on this.

**Comment by Bezaeel** [comment]
Yes

**Comment by perfectmak** [comment]
Some useful resources go go through in preparation to work on this issue:
- Metamasks Ethereum Provider Guide: https://docs.metamask.io/guide/ethereum-provider.html#using-the-provider
- Tutorial using web3-react to connect Metamask: https://medium.com/coinmonks/web3-react-connect-users-to-metamask-or-any-wallet-from-your-frontend-241fd538ed39
